[project]
name = "ml6-sensor-clustering"
version = "0.1.0"
description = "Sensor failure clustering system"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "ruff>=0.11.5",
    "mypy>=1.15.0",
    "types-requests>=2.31.0.20240427",
]
