[project]
name = "ml6-sensor-clustering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kafka-python>=2.1.5",
    "loguru>=0.7.3",
    "numpy>=2.2.4",
    "polars>=1.27.1",
    "sqlalchemy>=2.0.40",
]
