[project]
name = "ml6-sensor-clustering"
version = "0.1.0"
description = "Sensor failure clustering system"
requires-python = ">=3.10"
dependencies = [
    "mypy>=1.15.0",
    "ruff>=0.11.7",
    "types-requests>=2.32.0.20250328",
]
