global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "predictor"
    static_configs:
      - targets: ["sensor-predictor:8001"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
