apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-producer-sa
  namespace: sensors
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sensor-producer-role
  namespace: sensors
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-producer-binding
  namespace: sensors
subjects:
  - kind: ServiceAccount
    name: sensor-producer-sa
    namespace: sensors
roleRef:
  kind: Role
  name: sensor-producer-role
  apiGroup: rbac.authorization.k8s.io
