name: Producer Service CD

on:
  push:
    branches: [ main ]
    paths:
      - 'producer/**'
      - 'domain/**'
      - 'k8s/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: acrsensorclusteringtst
  AKS_CLUSTER_NAME: aks-sensor-clustering-tst
  AKS_RESOURCE_GROUP: rg-sensor-clustering-tst

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Login to Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ vars.ARM_CLIENT_ID }}
        tenant-id: ${{ vars.ARM_TENANT_ID }}
        subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

    # Configure Docker to use the Azure CLI credentials
    - name: Docker login to ACR
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: producer/Dockerfile
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/sensor-producer:${{ github.sha }}
          ${{ env.ACR_NAME }}.azurecr.io/sensor-producer:latest
    
    # Install kubelogin for AAD authentication
    - name: Install kubelogin
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'latest'
      
    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
    
    # Substitute environment variables in manifests
    - name: Substitute environment variables
      uses: danielr1996/envsubst-action@1.1.0
      with:
        input: k8s/producer-deployment.yaml
        output: processed-deployment.yaml
      env:
        KEY_VAULT_URL: ${{ vars.KEY_VAULT_URL }}
        EVENTHUB_NAMESPACE: ${{ vars.EVENTHUB_NAMESPACE }}
        ACR_NAME: ${{ env.ACR_NAME }}
        IMAGE_TAG: ${{ github.sha }}
    
    # Deploy to AKS using k8s-deploy action
    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: default
        manifests: processed-deployment.yaml
        action: deploy